# Python CircleCI 2.0 configuration file
#
# Check https://circleci.com/docs/2.0/language-python/ for more details

version: 2

jobs:

  ##############################################################
  test-vedo:

    machine:
      image: ubuntu-2004:current

    resource_class: medium

    environment:
      MPLBACKEND: "agg"
      DEBIAN_FRONTEND: "noninteractive"

    steps:
      - checkout

      - run:
          name: installing vedo
          command: |
            sudo apt-get update
            sudo apt install libgl1-mesa-dev xvfb -y
            pip3 install typing-extensions
            pip3 install vedo
            pip3 install matplotlib
            pip3 install scipy
            pip3 install --no-deps .

      - run:
          name: Run tests
          command: |
            cd
            cd project/tests/common
            source run_all.sh

      - store_artifacts:
          path: test-reports
          destination: test-reports



######################################################
workflows:
  version: 2
  build-stuff:
    jobs:
      - test-vedo




